vss_common_config:
  contactform__active_tab: edit-disclaimer
  phone: '+91 9XXXX XXXXX'
  email: hello.ar@VSS.com
  address: '772 Lyonwood Ave Walnut, CA 9187'
  disclaimer_title: 'Welcome to the Virtual Safe Space!'
  disclaimer_description:
    value: "<p>This is a safe space designed for you to connect with peers and discover interesting content/answers to your questions.</p>\r\n\r\n<p><strong>Disclaimer in arabic:</strong></p>\r\n\r\n<p>Your browser history can be monitored without your knowledge, we recommend browsing in incognito mode in order to stay safe online. Here is how you can go to incognito mode:</p>\r\n"
    format: full_html
  disclaimer_image:
    - '11'
  submit: 'Save configuration'
  form_build_id: form-KvJYYz-DYhlsCGLYR2pR-CJQd5BujBbUMXn_Y1D5Is8
  form_token: p6ozqhlyjVU0LKBpdtDQm1Jzobe8l8wv7Y2EC94wPGE
  form_id: vss_common_config_form
  op: 'Save configuration'
