vss_common_config:
  contactform__active_tab: edit-disclaimer
  phone: ''
  email: ''
  address: ''
  disclaimer_title: 'Welcome to the Virtual Safe Space!'
  disclaimer_description:
    value: "<p>This is a safe space designed for you to connect with peers and discover interesting content/answers to your questions.</p>\r\n\r\n<p><strong>Disclaimer:</strong></p>\r\n\r\n<p>Your browser history can be monitored without your knowledge, we recommend browsing in incognito mode in order to stay safe online. Here is how you can go to incognito mode:</p>\r\n"
    format: full_html
  disclaimer_image:
    - '11'
  submit: 'Save configuration'
  form_build_id: form-NBgM0OrSMbsSfSNxbEkWCjYohh0m_jJ269dsuXjrVy0
  form_token: 66gZUvjdcveAIDL7TL39CEB-UZwMfZ-_TjVanrettFs
  form_id: vss_common_config_form
  op: 'Save configuration'

