tips:
  vss:
    body: '¡Oye! Estoy aquí para ayudarlo a aprender cómo crear rápidamente un "espacio seguro virtual".'
  breadcrumb:
    label: 'migaja de pan'
    body: '¡Oye! Estoy aquí para ayudarlo a aprender a preparar rápidamente "migas de pan".'
  settings:
    label: ajustes
    body: '¡Oye! Estoy aquí para ayudarlo a aprender a "Menú de configuración" rápidamente.'
  copyright:
    label: 'derechos de autor'
    body: '¡Oye! Estoy aquí para ayudarlo a aprender a "Derechos de autor" rápidamente.'
