label: Watchdog
description: 'Recent log messages'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
          tags:
            previous: ‹‹
            next: ››
      fields:
        nothing:
          admin_label: Icon
        wid:
          label: WID
        severity:
          label: Severity
        type:
          label: Tipo
        timestamp:
          label: Fecha
        message:
          label: Message
          alter:
            alt: '{{ message }}'
        name:
          label: Usuario
          separator: ', '
        link:
          label: Operaciones
      filters:
        type:
          expose:
            label: Tipo
        severity:
          expose:
            label: Severity
      title: 'Recent log messages'
      empty:
        area:
          admin_label: 'No log messages available.'
          content: 'No log messages available.'
  page:
    display_title: Página
