label: 'Paragraphs library'
display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        label:
          label: Label
          separator: ', '
        type:
          label: Tipo
          separator: ', '
        paragraphs__target_id:
          label: Paragraphs
          separator: ', '
        langcode:
          label: Idioma
          separator: ', '
        id:
          label: ID
          separator: ', '
        count:
          label: Used
        changed:
          label: Changed
          separator: ', '
        operations:
          label: Operaciones
      filters:
        label:
          expose:
            label: Label
          group_info:
            label: Label
        type:
          expose:
            label: Tipo
      title: 'Paragraphs library'
      empty:
        area_text_custom:
          content: 'No library items available.'
  page_1:
    display_title: Página
