label: Contenido
description: 'Find and manage content.'
display:
  default:
    display_title: Master
    display_options:
      title: Contenido
      fields:
        title:
          label: Título
        type:
          label: 'Tipo de contenido'
          separator: ', '
        name:
          label: Autor
        status:
          label: Estado
          settings:
            format_custom_false: Unpublished
            format_custom_true: Published
        changed:
          label: Updated
        operations:
          label: Operaciones
      pager:
        options:
          tags:
            next: 'Siguiente >'
            previous: '‹ Anterior'
            first: '« Primero'
            last: 'Último »'
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      empty:
        area_text_custom:
          content: 'No content available.'
      filters:
        title:
          expose:
            label: Título
        type:
          expose:
            label: 'Tipo de contenido'
        status:
          expose:
            label: Estado
          group_info:
            label: 'Published status'
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
        langcode:
          expose:
            label: Idioma
  page_1:
    display_title: Página
    display_options:
      menu:
        title: Contenido
      tab_options:
        title: Contenido
        description: 'Find and manage content'
