label: 'Comentarios recientes'
description: 'Comentarios recientes.'
display:
  default:
    display_title: Master
    display_options:
      title: 'Comentarios recientes'
      empty:
        area_text_custom:
          content: 'No comments available.'
  block_1:
    display_title: Block
    display_options:
      block_description: 'Comentarios recientes'
      block_category: 'Listas (Views)'
