label: 'Media library'
description: 'Find and manage media.'
display:
  default:
    display_title: Master
    display_options:
      title: Multimedia
      fields:
        media_bulk_form:
          action_title: Acción
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      exposed_form:
        options:
          submit_button: 'Apply filters'
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      empty:
        area_text_custom:
          content: 'No media available.'
      sorts:
        created:
          expose:
            label: 'Newest first'
        name:
          expose:
            label: 'Name (A-Z)'
        name_1:
          expose:
            label: 'Name (Z-A)'
      filters:
        status:
          expose:
            label: 'Publishing status'
          group_info:
            label: Published
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
        name:
          expose:
            label: Nombre
        bundle:
          expose:
            label: 'Media type'
          group_info:
            label: 'Media type'
        langcode:
          expose:
            label: Idioma
  page:
    display_title: Página
    display_options:
      fields:
        media_bulk_form:
          action_title: Acción
        name:
          separator: ', '
        edit_media:
          alter:
            text: 'Edit {{ name }}'
            alt: 'Edit {{ name }}'
          text: Editar
        delete_media:
          alter:
            text: 'Delete {{ name }}'
            alt: 'Delete {{ name }}'
          text: Eliminar
  widget:
    display_title: Widget
    display_options:
      arguments:
        bundle:
          exception:
            title: Todo(s)
      filters:
        name:
          expose:
            label: Nombre
      header:
        display_link_grid:
          label: Grid
        display_link_table:
          label: Table
  widget_table:
    display_options:
      fields:
        thumbnail__target_id:
          label: Miniatura
        name:
          label: Nombre
        uid:
          label: Autor
        changed:
          label: Updated
      arguments:
        bundle:
          exception:
            title: Todo(s)
      filters:
        name:
          expose:
            label: Nombre
      header:
        display_link_grid:
          label: Grid
        display_link_table:
          label: Table
