label: 'Moderated content'
description: 'Find and moderate content.'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        title:
          label: Título
          separator: ', '
        type:
          label: 'Tipo de contenido'
          separator: ', '
        name:
          label: Autor
          separator: ', '
        moderation_state:
          label: 'Moderation state'
          separator: ', '
        changed:
          label: Updated
          separator: ', '
        operations:
          label: Operaciones
      filters:
        title:
          expose:
            label: Título
        type:
          expose:
            label: 'Tipo de contenido'
        moderation_state:
          expose:
            label: 'Moderation state'
        langcode:
          expose:
            label: Idioma
      title: 'Moderated content'
      empty:
        area_text_custom:
          content: 'No moderated content available. Only pending versions of content, such as drafts, are listed here.'
  moderated_content:
    display_title: 'Moderated content'
