label: People
description: 'Find and manage people interacting with your site.'
display:
  default:
    display_title: Master
    display_options:
      title: People
      fields:
        user_bulk_form:
          label: 'Bulk update'
        name:
          label: 'Nombre de usuario'
        status:
          label: Estado
          settings:
            format_custom_false: Blocked
            format_custom_true: Activo
        roles_target_id:
          label: Roles
        created:
          label: 'Member for'
        access:
          label: 'Last access'
        operations:
          label: Operaciones
        mail:
          separator: ', '
      pager:
        options:
          tags:
            next: 'Siguiente >'
            previous: '‹ Anterior'
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      empty:
        area_text_custom:
          content: 'No people available.'
      filters:
        combine:
          expose:
            label: 'Name or email contains'
        status:
          group_info:
            label: Estado
            group_items:
              1:
                title: Activo
              2:
                title: Blocked
        roles_target_id:
          expose:
            label: Role
        permission:
          expose:
            label: Permission
      use_more_text: more
  page_1:
    display_title: Página
    display_options:
      menu:
        title: List
        description: 'Find and manage people interacting with your site.'
      tab_options:
        title: People
        description: 'Manage user accounts, roles, and permissions.'
