display:
  page_1:
    display_title: 'إدارة أنواع الخدمات'
  default:
    display_options:
      title: 'إدارة أنواع الخدمات'
      header:
        result:
          content: '<div class="service-count more-link">@total أنواع الخدمات</div>'
