elements: |
  location:
    '#title': الموقع
    '#location_tid__title': ''
    '#attached__title': ''
  organisation:
    '#title': المنظمة
  opening_times:
    '#title': 'ساعات العمل'
    '#destination': {  }
  number_of_staff_providing_services:
    '#title': 'عدد الموظفين مقدمي الخدمة'
  transportation_available:
    '#title': 'المواصلات متوفرة'
  accessibility_for_persons:
    '#title': ':القدرة على دعم الإعاقات التالية'
  age_group:
    '#title': 'الفئة العمرية'
  target_group:
    '#title': 'الفئة المستهدفة'
  field_mode:
    '#title': 'نمط الخدمة'
  q_type_of_service_delivery_point_:
    '#title': 'نوع نقطة تقديم الخدمة'
  field_name_of_the_focal_point:
    '#title': 'اسم مسؤول التواصل لغرض الإحالة (الاسم الأول\الثاني)'
  field_phone_number_of_focal_poin:
    '#title': 'رقم هاتف مسؤول التواصل'
  field_email_of_focal_point:
    '#title': 'البريد الالكتروني لمسؤول التواصل'
  field_name_backup_focalpoint_ref:
    '#title': 'اسم مسؤول التواصل الاحتياطي'
  field_phone_number_backup_focalp:
    '#title': 'رقم هاتف مسؤول التواصل الاحتياطي'
  field_email_backup_focal_point:
    '#title': 'البريد الالكتروني لمسؤول التواصل الاحتياطي'
  erpw_workflow:
    '#description': "<br />\r\n<quillbot-extension-portal></quillbot-extension-portal>"
    '#more': "<br />\r\n<quillbot-extension-portal></quillbot-extension-portal>"
    '#admin_notes': "<br />\r\n<quillbot-extension-portal></quillbot-extension-portal>"
  service_type:
    '#title': 'نوع الخدمة'
