timeout: 2592000
max_timeout: 2592000
padding: 20
no_individual_logout_threshold: false
role_logout: false
role_logout_max: false
redirect_url: /user/login
no_dialog: false
dialog_title: 'Erefer Alert'
message: 'Your session is about to expire. Do you want to reset it?'
inactivity_message: 'You have been logged out due to inactivity.'
inactivity_message_type: status
disable_buttons: false
yes_button: ''
no_button: ''
enforce_admin: false
whitelisted_ip_addresses: ''
use_alt_logout_method: false
use_watchdog: true
