_core:
  default_config_hash: qxRdknZThnFBudeyxEFSc7ykDN2R19IbEYuIkGwkLa4
langcode: en
routes: "email_tfa.verifiy\r\nuser.logout"
timeouts: 300
subject: 'One Time Password'
body: "Dear [user:name],\r\n    \r\nYour One Time Password for completing your transaction Drupal TFA Verification is: [user:email_tfa]\r\n    \r\nPlease use this Password to complete your transaction. Do not share this password with anyone.\r\n    \r\nThank you,\r\n[site:name] team"
