description: 'بحث وإدارة الأشخاص المتفاعلين مع موقعك.'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: انتقاء
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          tags:
            previous: '‹ السابق'
            next: 'التالي ›'
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      fields:
        name:
          label: 'اسم المستخدم'
        status:
          label: الحالة
          settings:
            format_custom_true: نشط
            format_custom_false: ممنوع
        roles_target_id:
          label: الأدوار
        field_domain_access:
          separator: ', '
        field_domain_all_affiliates:
          separator: ', '
        created:
          label: 'مسجل بالموقع منذ'
        access:
          label: 'آخر وصول'
        operations:
          label: عمليات
        mail:
          separator: ', '
      filters:
        roles_target_id:
          expose:
            label: الدور
        permission:
          expose:
            label: الصلاحية
        status:
          group_info:
            label: الحالة
            group_items:
              1:
                title: نشط
              2:
                title: ممنوع
      title: الأشخاص
      empty:
        area_text_custom:
          content: 'لا يوجد أشخاص.'
      use_more_text: المزيد
  page_1:
    display_options:
      menu:
        title: لائحة
        description: 'بحث وإدارة الأشخاص المتفاعلين مع موقعك.'
      tab_options:
        title: الأشخاص
        description: 'إدارة حسابات المستخدمين والأدوار والصلاحيات.'
      arguments:
        field_domain_access_target_id:
          exception:
            title: الكل
  page_2:
    display_options:
      filters:
        roles_target_id:
          expose:
            label: الدور
        permission:
          expose:
            label: الصلاحية
        status:
          group_info:
            label: الحالة
            group_items:
              1:
                title: نشط
              2:
                title: ممنوع
        field_domain_access_target_id:
          expose:
            label: النطاق
