ignored_config_entities:
  - vss_common_config.vsscommonconfig
  - 'tour.tour.*'
  - 'block.block.iraqnavigationheadermenu.yml'
  - 'block.block.navigationheadermenu.yml'
_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
