text_resize_scope: 'body,button,p,h1,h2,h3,h4,h5,h6,b,strong,i,a,.discover'
text_resize_minimum: 12
text_resize_maximum: 25
text_resize_reset_button: false
text_resize_line_height_allow: true
text_resize_line_height_min: 16
text_resize_line_height_max: 36
_core:
  default_config_hash: Q9ktHJ11eYmt19RAlj_sgd6N4p0ywqDU4THcnhfl6q4
