favicon:
  mimetype: image/png
  path: profiles/unicef/themes/custom/vss_amp/images/favicon.png
  url: 'https://vss.lndo.site/sites/default/files/favicon_0.png'
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
schemas:
  bootstrap: 8000
  vss: 8000
fluid_container: 1
region_wells:
  navigation: ''
  navigation_collapsible: ''
  header: ''
  breadcrumb: ''
  highlighted: ''
  help: ''
  content: ''
  content_bottom: ''
  sidebar_first: ''
  sidebar_second: ''
  content_bottom_fluid: ''
  global_sticky: ''
  footer_top: ''
  footer: ''
reset_http_request_cache: ''
table: ''
