favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://vss.lndo.site/profiles/unicef/themes/custom/vss/favicon.ico'
  use_default: true
schemas:
  bootstrap: 8000
  vss: 8000
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
fluid_container: 1
table_responsive: '-1'
cdn_theme: bootstrap
cdn_cache_ttl_versions: '604800'
cdn_cache_ttl_themes: '604800'
cdn_cache_ttl_assets: '0'
cdn_cache_ttl_library: '0'
reset_http_request_cache: ''
table: ''
