display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: پاڵێو
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      fields:
        name:
          label: 'ناوی تێپەڕبوون'
        status:
          label: ڕەوش
          settings:
            format_custom_true: چالاکە
            format_custom_false: بلۆککراوە
        roles_target_id:
          label: ڕۆڵەکان
        operations:
          label: کاره‌کان
      filters:
        roles_target_id:
          expose:
            label: ڕۆل
        permission:
          expose:
            label: 'مۆڵەت پێدان'
        status:
          group_info:
            label: ڕەوش
            group_items:
              1:
                title: چالاکە
              2:
                title: بلۆککراوە
      title: خەڵک
      empty:
        area_text_custom:
          content: 'هیچ کەسێک نییە.'
      use_more_text: زیاتر
  page_1:
    display_options:
      menu:
        title: لیستە
      tab_options:
        title: خەڵک
        description: 'بەڕێوەبردنی هەژماری بەکارهێنەران، ڕۆڵەکان و مۆڵەتپێدانەکان.'
      arguments:
        field_domain_access_target_id:
          exception:
            title: هەموو
  page_2:
    display_options:
      filters:
        roles_target_id:
          expose:
            label: ڕۆل
        permission:
          expose:
            label: 'مۆڵەت پێدان'
        status:
          group_info:
            label: ڕەوش
            group_items:
              1:
                title: چالاکە
              2:
                title: بلۆککراوە
        field_domain_access_target_id:
          expose:
            label: دۆمەین
