settings:
  intro_text:
    value: "<p><img alt=\"icon\" src=\"/themes/custom/erpw/images/cross-white.svg\" /></p>\r\n\r\n<p>eRPW</p>\r\n\r\n<p>إضغط هنا لتنصيب تطبيق مسارات الإحالة الإلكتروني على جهازك</p>\r\n"
    format: full_html
