description: 'إيجاد وإدارة المحتوى'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: انتقاء
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          tags:
            previous: '‹ السابق'
            next: 'التالي ›'
      fields:
        title:
          label: العنوان
        type:
          label: 'نوع المحتوى'
          separator: ', '
        field_domain_access:
          separator: ', '
        field_domain_all_affiliates:
          separator: ', '
        name:
          label: المؤلف
        status:
          label: الحالة
          settings:
            format_custom_true: منشور
            format_custom_false: 'غير منشور'
        changed:
          label: التحديث
        operations:
          label: عمليات
      filters:
        status:
          expose:
            label: الحالة
          group_info:
            group_items:
              1:
                title: منشور
              2:
                title: 'غير منشور'
        type:
          expose:
            label: النوع
        title:
          expose:
            label: العنوان
        langcode:
          expose:
            label: اللغة
      empty:
        area_text_custom:
          content: 'لا يوجد محتوى.'
      arguments:
        field_domain_access_target_id:
          exception:
            title: الكل
    display_title: الرئيسي
  page_1:
    display_options:
      menu:
        title: المحتوى
      tab_options:
        title: المحتوى
      filters:
        status:
          expose:
            label: الحالة
          group_info:
            group_items:
              1:
                title: منشور
              2:
                title: 'غير منشور'
        type:
          expose:
            label: النوع
        title:
          expose:
            label: العنوان
        langcode:
          expose:
            label: اللغة
      title: المحتوى
  page_2:
    display_options:
      filters:
        status:
          expose:
            label: الحالة
          group_info:
            group_items:
              1:
                title: منشور
              2:
                title: 'غير منشور'
        type:
          expose:
            label: النوع
        title:
          expose:
            label: العنوان
        langcode:
          expose:
            label: اللغة
        field_domain_access_target_id:
          expose:
            label: النطاق
