label: 'أحدث التعليقات'
display:
  default:
    display_title: Master
    display_options:
      title: 'أحدث التعليقات'
      empty:
        area_text_custom:
          content: 'No comments available.'
  block_1:
    display_title: Block
    display_options:
      block_description: 'أحدث التعليقات'
