description: 'Find and manage people interacting with your site.'
display:
  default:
    display_title: الرئيسي
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      fields:
        name:
          label: 'اسم المستخدم'
        status:
          label: الحالة
          settings:
            format_custom_true: نشط
            format_custom_false: Blocked
        roles_target_id:
          label: الأدوار
        field_domain_access:
          separator: ', '
        field_domain_all_affiliates:
          separator: ', '
        created:
          label: 'Member for'
        access:
          label: 'Last access'
        operations:
          label: عمليات
        mail:
          separator: ', '
      filters:
        roles_target_id:
          expose:
            label: Role
        permission:
          expose:
            label: Permission
        status:
          group_info:
            label: الحالة
            group_items:
              1:
                title: نشط
              2:
                title: Blocked
      title: People
      empty:
        area_text_custom:
          content: 'No people available.'
      use_more_text: more
  page_1:
    display_options:
      menu:
        title: List
        description: 'Find and manage people interacting with your site.'
      tab_options:
        title: People
        description: 'Manage user accounts, roles, and permissions.'
      arguments:
        field_domain_access_target_id:
          exception:
            title: All
  page_2:
    display_options:
      filters:
        roles_target_id:
          expose:
            label: Role
        permission:
          expose:
            label: Permission
        status:
          group_info:
            label: الحالة
            group_items:
              1:
                title: نشط
              2:
                title: Blocked
        field_domain_access_target_id:
          expose:
            label: Domain
