label: ميديا
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
      fields:
        media_bulk_form:
          action_title: إجراء
        thumbnail__target_id:
          label: 'النسخة المصغرة'
          separator: ', '
        name:
          separator: ', '
        bundle:
          label: النوع
          separator: ', '
        uid:
          label: المؤلف
          separator: ', '
        status:
          label: الحالة
          settings:
            format_custom_true: Published
            format_custom_false: Unpublished
          separator: ', '
        changed:
          label: Updated
          separator: ', '
        operations:
          label: عمليات
      filters:
        bundle:
          expose:
            label: النوع
        status:
          expose:
            label: صحيح
          group_info:
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
        langcode:
          expose:
            label: اللغة
      title: ميديا
  media_page_list:
    display_title: ميديا
    display_options:
      menu:
        title: ميديا
