display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: تطبيق
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      fields:
        info:
          label: 'Block description'
          separator: ', '
        type:
          separator: ', '
        changed:
          label: Updated
        operations:
          label: عمليات
      filters:
        info:
          expose:
            label: 'Block description'
  page_1:
    display_title: الصفحة
