label: 'Recent content'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: تطبيق
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      fields:
        changed:
          separator: ', '
      title: 'Recent content'
      empty:
        area_text_custom:
          content: 'No content available.'
      use_more_text: More
  block_1:
    display_title: Block
