label: Comments
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          tags:
            previous: '‹ previous'
            next: 'next ›'
            last: 'last »'
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      fields:
        comment_bulk_form:
          action_title: إجراء
        subject:
          label: الموضوع
          separator: ', '
        uid:
          separator: ', '
        name:
          label: المؤلف
          separator: ', '
        entity_id:
          label: 'Posted in'
          separator: ', '
        changed:
          label: Updated
          separator: ', '
        operations:
          label: عمليات
        name_1:
          separator: ', '
      filters:
        subject:
          expose:
            label: الموضوع
        langcode:
          expose:
            label: اللغة
      title: Comments
      empty:
        area_text_custom:
          content: 'No comments available.'
      use_more_text: more
  page_published:
    display_title: 'Published comments'
    display_options:
      menu:
        title: Comments
        description: 'Comments published'
      display_description: 'The approved comments listing.'
  page_unapproved:
    display_title: 'Unapproved comments'
    display_options:
      menu:
        title: 'Unapproved comments'
        description: 'Comments unapproved'
      display_description: 'The unapproved comments listing.'
      filters:
        subject:
          expose:
            label: الموضوع
        langcode:
          expose:
            label: اللغة
      fields:
        comment_bulk_form:
          action_title: إجراء
        subject:
          label: الموضوع
          separator: ', '
        uid:
          separator: ', '
        name:
          label: المؤلف
          separator: ', '
        entity_id:
          label: 'Posted in'
          separator: ', '
        changed:
          label: Updated
          separator: ', '
        operations:
          label: عمليات
        name_1:
          separator: ', '
