display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: 'Apply filters'
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      fields:
        media_bulk_form:
          action_title: إجراء
      filters:
        status:
          group_info:
            label: Published
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
        name:
          expose:
            label: الاسم
        langcode:
          expose:
            label: اللغة
      title: ميديا
  page:
    display_title: الصفحة
    display_options:
      fields:
        media_bulk_form:
          action_title: إجراء
        name:
          separator: ', '
        edit_media:
          text: تحرير
        delete_media:
          text: حذف
  widget:
    display_title: Widget
    display_options:
      filters:
        name:
          expose:
            label: الاسم
      arguments:
        bundle:
          exception:
            title: All
      header:
        display_link_grid:
          label: Grid
        display_link_table:
          label: Table
  widget_table:
    display_options:
      fields:
        thumbnail__target_id:
          label: 'النسخة المصغرة'
        name:
          label: الاسم
        uid:
          label: المؤلف
        changed:
          label: Updated
      filters:
        name:
          expose:
            label: الاسم
      arguments:
        bundle:
          exception:
            title: All
      header:
        display_link_grid:
          label: Grid
        display_link_table:
          label: Table
