password_reset:
  body: |-
    [user:display-name],

    A request to reset the password for your account has been made at [site:name].

    You may now log in by clicking this link or copying and pasting it into your browser:

    [user:one-time-login-url]

    This link can only be used once to log in and will lead you to a page where you can set your password. It expires after one day and nothing will happen if it's not used.

    --  [site:name] team