display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filter
      fields:
        name:
          label: Username
        status:
          label: Status
        operations:
          label: Operations
      filters:
        status:
          group_info:
            label: Status
  page_1:
    display_options:
      menu:
        title: List
      arguments:
        field_domain_access_target_id:
          exception:
            title: All
  page_2:
    display_options:
      filters:
        status:
          group_info:
            label: Status
