label: Content
display:
  default:
    display_title: Default
    display_options:
      title: Content
      fields:
        status:
          label: Status
          settings:
            format_custom_true: Published
        operations:
          label: Operations
      exposed_form:
        options:
          submit_button: Filter
      filters:
        status:
          expose:
            label: Status
          group_info:
            group_items:
              1:
                title: Published
        langcode:
          expose:
            label: Language
  page_1:
    display_options:
      menu:
        title: Content
      tab_options:
        title: Content
