display:
  default:
    display_title: Default
    display_options:
      fields:
        operations:
          label: Operations
      exposed_form:
        options:
          submit_button: Filter
      filters:
        langcode:
          expose:
            label: Language
  page_unapproved:
    display_options:
      fields:
        operations:
          label: Operations
      filters:
        langcode:
          expose:
            label: Language
