display:
  default:
    display_title: ডিফল্ট
    display_options:
      fields:
        name:
          label: লেখক
        changed:
          label: 'সর্বশেষ আপডেট'
  attachment_1:
    display_title: সংযুক্তি
