third_party_settings:
  field_group:
    group_step_1_personal_details:
      label: 'Step 1: Personal details'
    group_step_2_geographical_covera:
      label: 'Step 2: Geographical coverage of your role'
content:
  field_position:
    settings:
      placeholder: 'Select position'
