body: "Dear [user:name],\r\n    \r\nYour One Time Password for completing your transaction eRPW TFA Verification is: [user:email_tfa]\r\n    \r\nPlease use this Password to complete your transaction. Do not share this password with anyone.\r\n    \r\nThank you,\r\n[site:name] team"
security_code_interrupt_text: বাতিল
