vss_common_config.vss_common_config_form:
  title: 'Vss Common Configuration Settings'
  route_name: vss_common_config.vss_common_config_form
  description: 'Common configuration for VSS site.'
  parent: system.admin_config_system
  weight: 99
