_core:
  default_config_hash: 6Ka3T1c-CIjEUO1Q64NXKksLthkMhj53a6zy4RJBtkc
verbose: 1
types:
  webform_submission: {  }
  block_content: {  }
  comment: {  }
  contact_message: {  }
  content_moderation_state: {  }
  location: {  }
  file: {  }
  menu_link_content: {  }
  node: {  }
  path_alias: {  }
  shortcut: {  }
  taxonomy_term: {  }
  user: {  }
  paragraph: {  }
types_translation_lock: {  }
types_js_lock: {  }
form_op_lock:
  block_content:
    mode: 0
    values: {  }
  comment:
    mode: 0
    values: {  }
  contact_message:
    mode: 0
    values: {  }
  content_moderation_state:
    mode: 0
    values: {  }
  location:
    mode: 0
    values: {  }
  file:
    mode: null
    values: {  }
  menu_link_content:
    mode: 0
    values: {  }
  node:
    mode: 0
    values: {  }
  path_alias:
    mode: 0
    values: {  }
  shortcut:
    mode: 0
    values: {  }
  taxonomy_term:
    mode: 0
    values: {  }
  user:
    mode: 0
    values: {  }
  webform_submission:
    mode: 1
    values:
      edit: edit
      edit_all: edit_all
      duplicate: duplicate
      delete: delete
  paragraph:
    mode: 0
    values: {  }
