_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: true
  user__page:
    menu_name: account
    parent: ''
    weight: -49
    expanded: false
    enabled: true
  user__logout:
    menu_name: account
    parent: ''
    weight: -44
    expanded: false
    enabled: true
  notification_entity__admin__structure__settings:
    parent: config_pages.notification_events
    menu_name: admin
    enabled: true
    expanded: false
    weight: 0
  notification_processed_entity__admin__structure__settings:
    weight: 1
    parent: config_pages.notification_events
    menu_name: admin
    expanded: false
    enabled: true
