_core:
  default_config_hash: cP1TZQyv1WdET3iepl2QoyOPK7VeO0xHm0lU_FU1Wmc
site_name: eRPW
short_name: eRPW
description: 'Referal Pathways'
start_url: /
scope: /
lang: en
theme_color: '#f9cdc4'
background_color: '#000000'
display: standalone
default_image: '0'
urls_to_cache: "/sign-up\r\n/sign-up?destination=/user-list\r\n/referral-pathway\r\n/services/426\r\n/services/431\r\n/services/436\r\n/services/441\r\n/services/446\r\n/services/451\r\n/user-location/0\r\n/user-location/1\r\n/user-location/10401\r\n/user-location/16821\r\n/user-location/10926\r\n/services/*\r\n/service-providers\r\n/dashboard\r\n/admin/structure/webform\r\n/manage-services\r\n/organisations\r\n/manage-service-types\r\n/manage-location\r\n/users-list\r\n/referral-pathway-listing\r\n/manage-draft-services"
urls_to_exclude: "admin/.*\r\nuser/.*"
offline_page: /offline
cache_version: '1'
cross_origin: false
skip_waiting: false
image: /sites/default/files/pwa/application_0.png
image_small: /sites/default/files/pwa/application_0.pngcopy.png
image_very_small: /sites/default/files/pwa/application_0.pngcopy2.png
