_core:
  default_config_hash: FLJZME3II5fjmMSrdEvJHp95ZJf8V_X0jbX0VdVU1BU
shield_enable: true
credential_provider: shield
credentials:
  shield:
    user: erpwadmin
    pass: 'Unicef#12345'
allow_cli: true
debug_header: false
unset_basic_auth_headers: true
print: Hello!
method: 0
paths: ''
allowlist: 127.0.0.1
http_method_allowlist: {  }
domains: "erpw.lndo.site\r\nzw.erpw.lndo.site\r\nbn.erpw.lndo.site"
