display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      fields:
        type:
          label: جۆر
        langcode:
          label: زمان
        operations:
          label: کاره‌کان
      filters:
        type:
          expose:
            label: جۆر
  page_1:
    display_title: پەڕە
