display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      fields:
        operations:
          label: کاره‌کان
  page_1:
    display_title: پەڕە
