description: 'Recent log messages'
display:
  default:
    display_title: Master
    display_options:
      title: 'Recent log messages'
      fields:
        severity:
          label: Severity
        type:
          label: جۆر
        timestamp:
          label: ڕێکەوت
        message:
          label: Message
        name:
          label: بەکارهێنەر
        link:
          label: کاره‌کان
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      empty:
        area:
          admin_label: 'No log messages available.'
          content: 'No log messages available.'
      filters:
        type:
          expose:
            label: جۆر
        severity:
          expose:
            label: Severity
  page:
    display_title: پەڕە
