display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      fields:
        title:
          label: ناونیشان
        name:
          label: نووسەر
  page_1:
    display_title: پەڕە
