display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
  block_1:
    display_options:
      block_category: بەکارهێنەر
