# This is a basic workflow to help you get started with Actions

name: Acquia application run security checks CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ devops ]
  pull_request:
    branches: [ devops ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  phpcs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['7.4']

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up PHP ${{ matrix.php_version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}

      - name: Install dependencies
        run: composer install --prefer-dist 

      - name: Run phpcs with Drupal coding standards.
        run: >
          ./vendor/bin/phpcs -p -s
      # ---- This will be uncommented for linter-----
      # - name: Run phplint with Drupal coding standards.
      #   run: > 
      #      ./vendor/bin/phplint 
      -  name: BLT  
         uses: actions/checkout@v2
      - name: Install SSH key for accessing Acquia Repository
        uses: shimataro/ssh-key-action@v2
        with:
            key: ${{ secrets.SSH_PRIVATE }}
            known_hosts: ${{ secrets.SSH_KNOWN_HOST }}
        
      - name: Setup PHP with PECL extension & Composer v1
        uses: shivammathur/setup-php@v2
        with:
            php-version: '7.4'
            tools: composer:v2
        
      # - name: Install composer dependencies
      #   run:  composer install --prefer-dist --no-progress
        
#         - name: Get Modifield files list
#           run: files= $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }});
        
      - name: Checkout modified files 
        run: git checkout .
          
      - name: Trigger BLT script to deploy to Acquia
        run:  blt artifact:deploy --commit-msg "Automated commit by BLT for Build" --branch $(echo ${GITHUB_REF#refs/heads/}) --no-interaction --verbose
           
      - name: Excecute Drush Commands at comstage21
        if: github.ref == 'refs/heads/localisation-stage'
        run : ./vendor/bin/drush @tracelink.comstage21 updb -y;  ./vendor/bin/drush @tracelink.comstage21 cim -y; ./vendor/bin/drush @tracelink.comstage21 cr -y; ./vendor/bin/drush @tracelink.comstage21 cohesion:rebuild -y; ./vendor/bin/drush @tracelink.comstage21 cr -y;
       
      - name: Excecute Drush Commands at comdev21
        if: github.ref == 'refs/heads/devops'
        run : ./vendor/bin/drush @tracelink.comdev21 updb -y;  ./vendor/bin/drush @tracelink.comdev21 cim -y; ./vendor/bin/drush @tracelink.comdev21 cr -y; ./vendor/bin/drush @tracelink.comdev21 cohesion:rebuild -y; ./vendor/bin/drush @tracelink.comdev21 cr -y;
           
        # - name: Deployment Status - Acquia BLT
        #   uses: ravsamhq/notify-slack-action@master
        #   if: always()
        #   with:
        #    status: ${{ job.status }}
        #    notification_title: '{workflow} has {status_message}'
        #    notify_when: 'success,failure,warnings'
        #   env:
        #    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} 